name: ShizukuExample Debug

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/debugCompile.yml
      - simple-implement/app/**
      - simple-implement/build.gradle.kts
      - simple-implement/gradle.properties
      - simple-implement/gradlew
      - simple-implement/gradlew.bat
      - simple-implement/settings.gradle.kts
      - adb-shell/app/**
      - adb-shell/build.gradle.kts
      - adb-shell/gradle.properties
      - adb-shell/gradlew
      - adb-shell/gradlew.bat
      - adb-shell/settings.gradle.kts

jobs:
  simple-implement-debug-apk:
    name: Build Simple Implement Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x simple-implement/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Build with Gradle
        id: gradle_build_debug
        run: ./simple-implement/gradlew assembleDebug -p simple-implement

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: simple-implement-debug
          path: simple-implement/app/build/outputs/apk/
          
  adb-shell-debug-apk:
    name: Build Package Installer Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x adb-shell/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Build with Gradle
        id: gradle_build_debug
        run: ./adb-shell/gradlew assembleDebug -p adb-shell

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: adb-shell-debug
          path: adb-shell/app/build/outputs/apk/        